### get
GET  http://localhost:3000/users 

###post
POST http://localhost:3000/users
Content-Type: application/json; charset=UTF-8

{
  "id"
}
###get
GET http://localhost:3000/users/3GET http://localhost:3000/users/3

###
DELETE http://localhost:3000/users/3